spring:
  thymeleaf:
    cache: false

server:
  port: 8099

  #logging:
#  level:
#    com:
#      github: ERROR




autogd:
  video:
    input-workspace: C:\Users\Arieh\Desktop\NewGD
    temp-workspace: ${autogd.video.input-workspace}\tmp
    resources:  ${autogd.video.input-workspace}\resources
    recordings: ${autogd.video.input-workspace}\recordings
    output: ${autogd.video.input-workspace}\video
    wav-target: ${autogd.video.input-workspace}\wav


    gdVideoStartTime: "00:22:53.5"
    gdVideoEndTime: "00:29:10.5"


    precodec-param: ""
    codec: "h264_nvenc"

  youtube:
    title: |-
     [%SERIES_TITLE_LANGUAGE_[%SERVICE_LANGUAGE%]%]: [%SERVICE_TITLE_BY_LANGUAGE_[%SERVICE_LANGUAGE%]%]
    description: |-
      Gottesdienst vom [%START_DATE%] mit [%PERSON_FIRST_NAME%] [%PERSON_LAST_NAME%]
      Silbern Church, Dietikon

      Bleib mit uns in Verbindung:
      Kontaktformular: https://www.silbern.church/kontakt/#kontaktformular
      https://www.instagram.com/silbern.church
      https://www.facebook.com/silbern

      Als Kirche erleben wir heute noch, wie Gott Herzen berührt, Gebete beantwortet, Wunder tut und Menschen verändert.

      Mehr über die Silbern Church: https://www.silbern.church/
      Möchtest du die Silbern Church unterstützen? https://www.silbern.church/spenden/
    tags:
      - Gottesdienst
      - Church
      - Service
      - Silbern Church
    for-kids: false
    privacy-status: public
  gdverwaltung:
    token: "6yZcTOhgWPKDmAc1t5PbtubV59Vkz8LSgI3r09zk"
    select:
      location: "Silbern"
      date: "02.03.2025"
      time: "11:00"

  podcast:
    domain: download.meine.church
    port: 21
    path: /web/media/silbern/mp3/
    username: ftpuploader
    password: C6yt@Sby%tt_ZHRt
